---

- hosts: all
  become: true
  tasks:
  
  - name: install dependencies
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg-agent
      state: present
      update_cache: yes