---

- hosts: all
  become: true
  tasks: 

  - name: update repository index
    apt:
      update_cache: yes

  - name: install python3 package
    apt:
      name: python3

  - name: install python3-pip package
    apt:
      name: python3-pip

  - name: install ca-certificates package dependency for docker
    apt:
      name: ca-certificates

  - name: install curl package dependency for docker
    apt:
      name: curl

  - name: install gnupg package dependency for docker
    apt:
      name: gnupg

  - name: install zip package
    apt:
      name: zip

  - name: install unzip package
    apt:
      name: unzip

  - name: install snap package
    apt:
      name: snap
